### ISSUE TITLE
SimpleSAML_exception_handler

### ISSUE THREAD

**Issue by codedev900** [kenchan0130/docker-simplesamlphp#38]
I tried enabling LDAP but getting this error message:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Error: Call to undefined function SimpleSAML\Module\ldap\Auth\ldap_connect()
Backtrace:
6 modules/ldap/lib/Auth/Ldap.php:96 (SimpleSAML\Module\ldap\Auth\Ldap::__construct)
5 modules/ldap/lib/ConfigHelper.php:201 (SimpleSAML\Module\ldap\ConfigHelper::login)
4 modules/ldap/lib/Auth/Source/LDAP.php:58 (SimpleSAML\Module\ldap\Auth\Source\LDAP::login)
3 modules/core/lib/Auth/UserPassBase.php:318 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
2 modules/core/www/loginuserpass.php:84 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by kenchan0130** [comment]
@codedev900 

What specific configuration file did you mount and run?
Please let me know, because without reproduction procedures I cannot debug either.

**Comment by codedev900** [comment]
Issue fixed. I needed to install the PHP LDAP module.
