### ISSUE TITLE
Could you release v1.19.7?

### ISSUE THREAD

**Issue by tatematsu-k** [kenchan0130/docker-simplesamlphp#41]
Thank you for publishing a useful Docker image.

I'm having trouble with [this issue](https://github.com/simplesamlphp/simplesamlphp/issues/1592).
So, Could you release v1.19.7 there?

https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.19.7

https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.19.6

**Comment by kenchan0130** [comment]
Thank you for your patience.
I have released

https://hub.docker.com/layers/kenchan0130/simplesamlphp/1.19.6/images/sha256-13562a8760a96464c074f9767e1ec20f5e60645e95308da8488ae889e3f47b24?context=explore

https://hub.docker.com/layers/kenchan0130/simplesamlphp/1.19.7/images/sha256-c02f79e4d56a86549672c7988b4bf2e2fff0b8d804619fb2cff686e95bd20a06?context=explore

**Comment by tatematsu-k** [comment]
Thank you for your release!
